"""Narrative enhancement orchestration.

The :class:`Enhancer` fills and polishes the report's prose sections. Its behaviour
depends on the configured provider:

* **LLM provider available** — each narrative section and each finding is rewritten /
  generated by the model (one model call per finding, plus three report-level calls).
  If a call fails, the enhancer degrades to the deterministic fallback for the rest of
  the run rather than erroring.
* **Offline / unavailable** — only *missing* prose is filled from deterministic
  templates; prose already supplied by the inputs is preserved verbatim.

This realizes the design goal: structured data fills the fields, the LLM improves the
prose, and the tool still produces a complete, readable report with no model at all.
"""

from __future__ import annotations

from typing import Optional

from ..config import LLMSettings, get_settings
from ..logging_config import get_logger
from ..models import Finding, NormalizedReport
from .base import LLMProvider, ProviderError
from .prompts import (
    fallback_conclusion,
    fallback_description,
    fallback_executive_summary,
    fallback_impact,
    fallback_methodology,
    fallback_remediation,
    finding_prompt,
    narrative_prompt,
    parse_finding_response,
)
from .providers import AnthropicProvider, OfflineProvider, OllamaProvider, OpenAIProvider

logger = get_logger(__name__)

_NARRATIVE_FALLBACKS = {
    "executive_summary": fallback_executive_summary,
    "methodology": fallback_methodology,
    "conclusion": fallback_conclusion,
}


def build_provider(settings: LLMSettings) -> LLMProvider:
    """Instantiate the provider named in settings (defaults to offline)."""
    name = (settings.provider or "offline").lower()
    common = dict(model=settings.model, max_tokens=settings.max_tokens, timeout=settings.timeout)
    if name == "anthropic":
        return AnthropicProvider(api_key=settings.api_key, **common)
    if name == "openai":
        return OpenAIProvider(
            api_key=settings.api_key,
            base_url=settings.base_url,
            temperature=settings.temperature,
            **common,
        )
    if name == "ollama":
        return OllamaProvider(
            base_url=settings.base_url, temperature=settings.temperature, **common
        )
    if name != "offline":
        logger.warning("Unknown LLM provider %r; using offline.", name)
    return OfflineProvider()


class Enhancer:
    """Fills and polishes the narrative sections of a :class:`NormalizedReport`."""

    def __init__(
        self,
        settings: Optional[LLMSettings] = None,
        provider: Optional[LLMProvider] = None,
    ) -> None:
        self.settings = settings or get_settings().llm
        self.provider = provider or build_provider(self.settings)
        # Use the LLM only if enhancement is enabled, the provider is a real LLM, and
        # it is actually usable right now.
        self._use_llm = (
            self.settings.enabled and self.provider.is_llm and self.provider.available()
        )

    @property
    def mode(self) -> str:
        if not self.settings.enabled:
            return "disabled"
        return f"llm:{self.provider.name}" if self._use_llm else "offline"

    def enhance_report(self, report: NormalizedReport) -> NormalizedReport:
        """Enhance the report in place and return it."""
        if not self.settings.enabled:
            logger.info("LLM enhancement disabled; narrative left unchanged.")
            return report

        logger.info(
            "Enhancing narrative for %d finding(s) (mode=%s)", len(report.findings), self.mode
        )

        metadata = report.metadata
        metadata.executive_summary = self._narrative(
            "executive_summary", metadata.executive_summary, report
        )
        metadata.methodology = self._narrative("methodology", metadata.methodology, report)
        metadata.conclusion = self._narrative("conclusion", metadata.conclusion, report)

        for finding in report.findings:
            self._enhance_finding(finding)

        return report

    # ------------------------------------------------------------------ #

    def _narrative(self, kind: str, existing: str, report: NormalizedReport) -> str:
        fallback = _NARRATIVE_FALLBACKS[kind]
        if self._use_llm:
            system, user = narrative_prompt(kind, existing, report)
            generated = self._safe_generate(system, user)
            if generated:
                return generated
        # Offline / fallback: preserve existing prose, otherwise synthesize.
        return existing if existing and existing.strip() else fallback(report)

    def _enhance_finding(self, finding: Finding) -> None:
        if self._use_llm:
            system, user = finding_prompt(finding)
            generated = self._safe_generate(system, user)
            if generated:
                parsed = parse_finding_response(generated)
                if parsed["description"]:
                    finding.description = parsed["description"]
                if parsed["impact"]:
                    finding.impact = parsed["impact"]
                if parsed["remediation"]:
                    finding.remediation = parsed["remediation"]

        # Ensure no prose field is left empty (covers offline mode and partial LLM output).
        if not finding.description.strip():
            finding.description = fallback_description(finding)
        if not finding.impact.strip():
            finding.impact = fallback_impact(finding)
        if not finding.remediation.strip():
            finding.remediation = fallback_remediation(finding)

    def _safe_generate(self, system: str, user: str) -> str:
        """Call the provider, returning '' (and disabling further LLM use) on failure."""
        try:
            return self.provider.generate(system, user).strip()
        except ProviderError as exc:
            logger.warning("LLM call failed (%s); falling back to deterministic prose.", exc)
            # Stop hammering a broken provider — use offline fallbacks for the rest.
            self._use_llm = False
            return ""
